# Generated by Django 2.1.5 on 2020-06-17 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='DishType',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='food',
            new_name='pizzas',
        ),
        migrations.AddField(
            model_name='pizzaprice',
            name='n_tops',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub',
            name='addons',
            field=models.ManyToManyField(to='orders.Sub_addon'),
        ),
        migrations.AddField(
            model_name='order',
            name='pastas',
            field=models.ManyToManyField(to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='order',
            name='plates',
            field=models.ManyToManyField(to='orders.Plate'),
        ),
        migrations.AddField(
            model_name='order',
            name='salads',
            field=models.ManyToManyField(to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='order',
            name='subs',
            field=models.ManyToManyField(to='orders.Sub'),
        ),
    ]
