# Generated by Django 2.1.5 on 2020-06-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200622_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.AlterField(
            model_name='sub',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Sub_main'),
        ),
    ]
