# Generated by Django 2.1.5 on 2020-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200622_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_main',
            old_name='price',
            new_name='price_l',
        ),
        migrations.RemoveField(
            model_name='sub_main',
            name='size',
        ),
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_main',
            name='price_s',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sub_main',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
