# Generated by Django 2.1.5 on 2020-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200622_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_main',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
