# Generated by Django 2.1.5 on 2020-06-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200622_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_main',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_main',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
