# Generated by Django 2.1.5 on 2020-06-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200622_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_main',
            name='size',
        ),
    ]
