# Generated by Django 2.1.5 on 2020-06-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_sub_main_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaladOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='salads',
        ),
        migrations.AddField(
            model_name='order',
            name='salads',
            field=models.ManyToManyField(through='orders.SaladOrder', to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='saladorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='saladorder',
            name='salad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Salad'),
        ),
    ]
