# Generated by Django 2.1.5 on 2020-06-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200623_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        # migrations.AlterField(
        #     model_name='order',
        #     name='pastas',
        #     field=models.ManyToManyField(through='orders.PastaOrder', to='orders.Pasta'),
        # ),
        migrations.RemoveField(
            model_name = "order",
            name = "pastas",
        ),
        migrations.AddField(
            model_name = "order",
            name = "pastas",
            field = models.ManyToManyField(through='orders.PastaOrder', to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='pastaorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='pastaorder',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pasta'),
        ),
    ]
