# Generated by Django 2.1.5 on 2020-07-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200629_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='price',
        ),
    ]
