# Generated by Django 2.1.5 on 2020-07-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rightssupport'),
        ('orders', '0014_remove_sub_price'),
    ]

    operations = [
    ]
