# Generated by Django 2.1.5 on 2020-07-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_merge_20200721_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.AddField(
            model_name='plate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='plateorder',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Plate'),
        ),
    ]
