# Generated by Django 2.1.5 on 2020-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200722_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='type',
            field=models.CharField(max_length=64),
        ),
    ]
